### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by scottgonzalez** [airportyh/browseroverflow#6]
Hey @airportyh. Would you be interested in collaborating on https://www.npmjs.com/package/browserstack rather than maintaining your own module? Having several browserstack modules on npm forces users to evaluate the available options, which can result in lots of cumulative wasted time for developers. Working together to build a best of breed module would improve the situation for the whole community.

**Comment by airportyh** [comment]
Hey @scottgonzalez thanks for the consideration! At the moment I am not really spending anytime on this module anymore, but merely taking PRs from other individuals. I'd be happy to link to your module.

**Comment by scottgonzalez** [comment]
That would be great, especially if there isn't much work going on in this repo. From the readme, it looks like there are just a few convenience methods that build on top of my existing module. I'd be happy to discuss adding features to the browserstack module. Do you want to [file some issues](https://github.com/scottgonzalez/node-browserstack/issues/new) for the features you're interested in?

**Comment by scottgonzalez** [comment]
I'd also be happy to bundle a CLI script in the browserstack module based on your browserstack-cli module.

**Comment by airportyh** [comment]
Added a link to your module! https://github.com/airportyh/browseroverflow

**Comment by scottgonzalez** [comment]
Thanks! @jzaefferer just pointed out that the npm package should be marked as deprecated so this information is available programmatically too. See https://docs.npmjs.com/cli/deprecate for details.
